// <auto-generated />
using Api.Productos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Productos.Migrations
{
    [DbContext(typeof(ProductosDbContext))]
    [Migration("20260408144741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Productos.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "Computadoras",
                            Codigo = "PROD-001",
                            Descripcion = "Laptop de alto rendimiento con pantalla OLED 4K",
                            Nombre = "Laptop Dell XPS 15",
                            Precio = 1899.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "Periféricos",
                            Codigo = "PROD-002",
                            Descripcion = "Mouse inalámbrico ergonómico de alta precisión",
                            Nombre = "Mouse Logitech MX Master 3",
                            Precio = 99.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "Periféricos",
                            Codigo = "PROD-003",
                            Descripcion = "Teclado mecánico inalámbrico con switches Brown",
                            Nombre = "Teclado Mecánico Keychron K2",
                            Precio = 89.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "Monitores",
                            Codigo = "PROD-004",
                            Descripcion = "Monitor 4K UHD de 27 pulgadas con USB-C",
                            Nombre = "Monitor LG 27UL850",
                            Precio = 449.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = "Periféricos",
                            Codigo = "PROD-005",
                            Descripcion = "Cámara web Full HD 1080p con micrófono estéreo",
                            Nombre = "Webcam Logitech C920",
                            Precio = 79.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = "Audio",
                            Codigo = "PROD-006",
                            Descripcion = "Audífonos over-ear con cancelación de ruido activa",
                            Nombre = "Audífonos Sony WH-1000XM5",
                            Precio = 349.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Categoria = "Accesorios",
                            Codigo = "PROD-007",
                            Descripcion = "Cable HDMI 2.1 de 2 metros, soporta 8K@60Hz",
                            Nombre = "Cable HDMI 2.1 Ultra High Speed",
                            Precio = 19.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Categoria = "Almacenamiento",
                            Codigo = "PROD-008",
                            Descripcion = "Unidad de estado sólido NVMe PCIe 4.0, lectura 7450 MB/s",
                            Nombre = "SSD Samsung 990 Pro 1TB",
                            Precio = 159.99m,
                            Stock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
